### ISSUE TITLE
Player standing in front of the Pokemon without entering the combat

### ISSUE THREAD

**Issue by monkeybee11** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#1]
not sure if its me that did something wrong or not but running the program im just standing infront of shymin its not doing anything 

quick video snip of just standing 
https://youtu.be/6skGPBFaokw

**Comment by Dinones** [comment]
Does this bug always occur, after a long time running or randomly?

**Comment by Lurkaplays** [comment]
This happened to me when "TV Output -> Adjust Screen Size" in the switch settings wasn't set to 100%. This was causing the black bars shown in the video.

I assume the program is looking for a pixel at the bottom that never appears on screen sizes less than 100%.

**Comment by monkeybee11** [comment]
> Does this bug always occur, after a long time running or just randomly?

it happened as soon as ive started the program

it connects the controller
exits the controller menu
starts up the pokemon game
gets past the "press a screen"
then just stands there in the field

**Comment by monkeybee11** [comment]
> This happened to me when "TV Output -> Adjust Screen Size" in the switch settings wasn't set to 100%. This was causing the black bars shown in the video.
> 
> I assume the program is looking for a pixel at the bottom that never appears on screen sizes less than 100%.

now that you say that mine is set to 94% to fit my tv moninter 🤔

**Comment by Lurkaplays** [comment]
> 

Are the black bars around the game in the preview gone?

**Comment by monkeybee11** [comment]
> > now that you say that mine is set to 94% to fit my tv moninter 🤔
> > no even setting it to 100% its still just not pressing A on shaymin
> 
> Are the black bars around the game in the preview gone?

beleave so.....didt relize what u ment till a moment a go XD ive allready unpluged the swich from my pi so be kinda anoying to set it all up a gen just to unplug it all XD)
 after ive got this shaymin im gonna try the program agen with heatran 
 shiny shaymin is like a light blue colour so im wondering if the program thinks its looking at the shiny bc of the bluw flowers in the field 🤔

**Comment by Dinones** [comment]
> > Does this bug always occur, after a long time running or just randomly?
> 
> it happened as soon as ive started the program
> 
> it connects the controller exits the controller menu starts up the pokemon game gets past the "press a screen" then just stands there in the field
> 
> wondering if it has anything to do with shaymins shiny colour being very close to the colours of the flowers so the program thinks its looking at a shiny shaymin
> 
> no idea if this will help or not but if it is colour related this was the settings me got using the sliders for about 5mins lower 182,193,0
> 
> upper 200,255,133

So as I understand, it presses HOME, then closes the game and restarts it successfully, but does not press A.

This issue is not related with the colors of shaymin. It only uses pokemon color detection once in the combat. The program detects the game has fully load checking if one corner pixel is black. It may be possible that if you don't have the "Screen Size" set as 100%, the corner pixel is always black even if the game is loaded. This will cause the program wait forever

**Comment by Dinones** [comment]
> This happened to me when "TV Output -> Adjust Screen Size" in the switch settings wasn't set to 100%. This was causing the black bars shown in the video.
> 
> I assume the program is looking for a pixel at the bottom that never appears on screen sizes less than 100%.

Did not even know this was an option, will mention it in the instructions in future versions. Thank you!

**Comment by monkeybee11** [comment]
> his issue is not related with the colors of shaymin. It only uses pokemon color detection once in the combat. The program detects the game has fully load checking if one corner pixel is black. It may be possible that if you don't have the "Screen Size" set as 100%, the corner pixel is always black even if the game is loaded. This will cause the program wait forever

ill make a new youtube video tomroeoh showing what im doing from start :P just to clear up everything

ive allready tryed it with the swich tv setting thing set to 100%

same as before it just stands there next to shaymin never starting a single encounter S:

**Comment by monkeybee11** [comment]
ok made a new recording of using the program from start to see if it is a user error and the TV setting is set to 100% size 

https://youtu.be/PBWGDkk0rBQ

**Comment by Dinones** [comment]
> ok made a new recording of using the program from start to see if it is a user error and the TV setting is set to 100% size
> 
> https://youtu.be/PBWGDkk0rBQ (un related note plz ignore the laggyness of my pi .... im pritty sure its related to the VNC its been playing up since ive "reformated" the pi)

That should definitely not be happening, can you add this line `print(f'{image.check_pixel_color()}')` above line 79 in `Shiny_Hunter.py`? This will print the color the program is detecting, which should be different from [0, 0, 0] when the game has loaded. If the color is that one, you can try changing line 109 of `Utils/Image_Processing.py` from `def check_pixel_color(self, pixel = [-1, 0]):` to `def check_pixel_color(self, pixel = None):`. This should make the program detect automatically the middle pixel of the image instead of the corner.

**Comment by monkeybee11** [comment]
> > ok made a new recording of using the program from start to see if it is a user error and the TV setting is set to 100% size
> > https://youtu.be/PBWGDkk0rBQ (un related note plz ignore the laggyness of my pi .... im pritty sure its related to the VNC its been playing up since ive "reformated" the pi)
> 
> That should definitely not be happening, can you add this line `print(f'{image.check_pixel_color()}')` above line 79 in `Shiny_Hunter.py`? This will print the color the program is detecting, which should be different from [0, 0, 0] when the game has loaded. If the color is that one, you can try changing line 109 of `Utils/Image_Processing.py` from `def check_pixel_color(self, pixel = [-1, 0]):` to `def check_pixel_color(self, pixel = None):`. This should make the program automatically detect the middle pixel of the image instead of the corner.

that debug print is printing out [0 0 0]

changing line 109 of the image prosessing file did start the pokemon battle with shaymin BUT....it crashed shortly after XD

Traceback (most recent call last):
  File "/home/monkeybee11/Nintendo-Switch-Pokemon-Shiny-Hunter/Shiny_Hunter.py", line 105, in <module>
    if attempts - initial_attempts >= CONST.AUTORESTART_ATTEMPTS: 
AttributeError: module 'Constants' has no attribute 'AUTORESTART_ATTEMPTS
`

**Comment by Dinones** [comment]
This is a bug I'm aware of... It'll be solved in the next version, for now you can follow the steps of issue #2 and change it manually.

**Comment by monkeybee11** [comment]
ok yea me remembered seeing that crash in the other issue 

but yea the swich is set to 100% when its pluged in to my pi4 ..... monkey is juse one of thos ppl that run in to bugs that dont happen to other ppl XD

**Comment by monkeybee11** [comment]
> This is a bug I'm aware of... It'll be solved in the next version, for now you can follow the steps of issue #2 and change it manually. Not sure why this is happening to you if you have the screen size to 100%, there are other points of the program where it checks that pixel, I'm not sure if it will be solved at all.

yea ok so im assuming this is one of thos other checks u said  just got around to applying the things said in the other issue and its just "afk" at the pokemon fight now XD not pressing home

**Comment by Dinones** [comment]
> > This is a bug I'm aware of... It'll be solved in the next version, for now you can follow the steps of issue #2 and change it manually. Not sure why this is happening to you if you have the screen size to 100%, there are other points of the program where it checks that pixel, I'm not sure if it will be solved at all.
> 
> yea ok so im assuming this is one of thos other checks u said just got around to applying the things said in the other issue and its just "afk" at the pokemon fight now XD not pressing home

Did it print that it detected a shiny? When a shiny is detected it stays 1 minute in the combat recording a video. If it detected as shiny and it's not, maybe the color thresholds are not accurate enough.

**Comment by Lurkaplays** [comment]
> Did it print that it detected a shiny? When a shiny is detected it stays 1 minute in the combat recording a video. If it detected a shiny and it's not, maybe the color thresholds are not accurate enough.

I have this issue myself and just assumed it was a weird bug. From my experience the console said nothing at all and just sat there without taking a screenshot or incrementing the counter.

I'll have a go at debugging after uni. Do you have any initial ideas where the issue could be stemming from?

**Comment by Dinones** [comment]
> > Did it print that it detected a shiny? When a shiny is detected it stays 1 minute in the combat recording a video. If it detected a shiny and it's not, maybe the color thresholds are not accurate enough.
> 
> I have this issue myself and just assumed it was a weird bug. From my experience the console said nothing at all and just sat there without taking a screenshot or incrementing the counter.
> 
> I'll have a go at debugging after uni. Do you have any initial ideas where the issue could be stemming from?

Using a Raspberry sometimes causes some buttons to not press correctly, that's why I added some checkpoints like the one of the home screen. Running it on the virtual machine (in a computer) solves this issue. You can add some extra time time to the macro before pressing one button. But as you say, if it does not print anything it may not be caused by the controller. Does it happen always or randomly?

**Comment by Lurkaplays** [comment]
> You can add some extra time time to the macro before pressing one button.

I can try this a bit later.



> Does it happen always or randomly?

Always.

**Comment by monkeybee11** [comment]
> > > This is a bug I'm aware of... It'll be solved in the next version, for now you can follow the steps of issue #2 and change it manually. Not sure why this is happening to you if you have the screen size to 100%, there are other points of the program where it checks that pixel, I'm not sure if it will be solved at all.
> > 
> > 
> > yea ok so im assuming this is one of thos other checks u said just got around to applying the things said in the other issue and its just "afk" at the pokemon fight now XD not pressing home
> 
> Did it print that it detected a shiny? When a shiny is detected it stays 1 minute in the combat recording a video. If it detected a shiny and it's not, maybe the color thresholds are not accurate enough.

ah ..... didt know that ....didt give it a full minnet of waiting but nothing was being said in the CMD at all and ive disabled video recording and screenshots 🤔

**Comment by monkeybee11** [comment]
gonna lable this one as fixed now :P seeing its been working since you updated the code ....then broke it with that bug that made it go in to a statis for wild hunts >.> but then u fixed it agen 😂  (but ill leave it to you to close the issue incase u know something thats still needs fixing related to this 👍
