### ISSUE TITLE
Crashing when using 'python3 Switch_Controller.py'

### ISSUE THREAD

**Issue by Xion3582** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#12]
When I use 'python3 Switch_Controller.py', then puts '1', the VM just crashes; my dongle is connected, i'm on the change order screen, asking me to press L and R, the controllers have no lights so they're not connected to the switch

**Comment by Dinones** [comment]
Thank you for reporting the issue. May I ask you some questions:

1. When you launch your VM, does your Bluetooth card appear ticked, as shown in the following image? _Note it may have a different name from mine._
  ![image](https://github.com/user-attachments/assets/30556722-83ed-40bc-aa66-21e8459da877)
2. Does the Bluetooth symbol appear in the top-right menu of your VM?
![image](https://github.com/user-attachments/assets/f10ccfff-97a1-4361-9c7e-2838c5088e0c)
3. Does the requirements installation `sudo pip install -r Requirements.txt && pip install -r Requirements.txt ` raise any error when you run it? You can run it again, it will not break anything.
4. If you open a terminal and run the test for the nxbt library `sudo nxbt demo` does it still crash? _Note your Nintendo Switch must be in the "Change Grip/Order" pairing menu as you did before._

**Comment by Xion3582** [comment]
Hello, it didn't work before but now for some reason, without me changing anything, it seems to work..
I just have a question, is it possible to hunt for Arceus with this ? If so, what should i choose ? Because I can't put myself in front of Arceus so i can't put it as a static encounter

**Comment by Xion3582** [comment]
> Hello, it didn't work before but now for some reason, without me changing anything, it seems to work.. I just have a question, is it possible to hunt for Arceus with this ? If so, what should i choose ? Because I can't put myself in front of Arceus so i can't put it as a static encounter

Also, whenever i try the program, it will automatically try to restart the game, and then it won't wait for the starting screen to happen, and immediately restarts the game

**Comment by Xion3582** [comment]
Fixed itself
