### ISSUE TITLE
Can't get VBox to recognize Elgato HD60 as webcam

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#13]
It only shows a blue screen of death and it only recognizes the USB not as a webcam. It shows VTubeStudio as the only available webcam.

**Comment by Dinones** [comment]
Thank you for reporting! I added an update to increase the FPS even when using the capture card as a USB device instead of a webcam.

Can you please try adding it as a USB Device and tell me if the FPS are high?

**Comment by RandomizerGamerRIPLinky** [comment]
FPS is at a solid 5fps, it won't let me use Shiny_Hunter.py without using the vtubestudio webcam

**Comment by RandomizerGamerRIPLinky** [comment]
[Uploading Shiny Hunt Automation-screen0.webm…]()

**Comment by RandomizerGamerRIPLinky** [comment]
Hopefully the video I sent helps. If need be, I can do other steps if I'm potentially doing something wrong.

**Comment by RandomizerGamerRIPLinky** [comment]
[Shiny Hunt Automation-screen0.webm](https://github.com/user-attachments/assets/18beb175-5247-462b-840b-1898d3f7ff6a)

**Comment by RandomizerGamerRIPLinky** [comment]
Video is sent, had to move it from my thumb drive to my drive lol

**Comment by RandomizerGamerRIPLinky** [comment]
Does the video work at all?

**Comment by RandomizerGamerRIPLinky** [comment]
[Shiny Hunt Automation-screen0.webm](https://github.com/user-attachments/assets/6c3ed2a7-3b1c-4c1d-90b1-ac3107526346)

**Comment by RandomizerGamerRIPLinky** [comment]
Corrupt JPEG data: 122698 extraeous bytes before marker oxd9 is being spammed when I try to use Shiny_Hunter.py if you're not able to see the video.

**Comment by Dinones** [comment]
Hi! Thank you for your answers! I am unable to see the videos (you can upload them as a private video on youtube if you want). May I answer some questions:

1. The point is that the Webcams section does not appear to you, or that it appears but does not detect the ElGato capture card as a webcam?
2. When connecting your capture card as a USB device, can you open a terminal in the `Modules/` folder and run the following command: `python3 Game_Capture.py`. Select the _"Check current capture device"_ option. What FPS do you get?
3. You said you had a _vtubestudio webcam_. Can you please retry the previous step with it instead of the capture card. What are the FPS for this device?

**Comment by RandomizerGamerRIPLinky** [comment]
It provides a blue screen and gives anywhere from 3-5 FPS without the capture card as a USB

**Comment by RandomizerGamerRIPLinky** [comment]
If you download the video, it works. Not sure why it's like that

**Comment by Dinones** [comment]
Let's check step by step what is happening here:

1. Make sure you have all the necessary packages installed on your VM. Open a terminal and run the following commands one by one:
   ```
   sudo apt-get update
   sudo apt-get install build-essential libopencv-dev python3-opencv v4l-utils
   ```
2. We will use v4l2-ctl to check if the device is recognized and to list available formats:
   ```
   v4l2-ctl --list-devices
   ```
   This will show a list of all the available devices. Now run the following command replacing the _X_ by the number of your device:
   ```
   v4l2-ctl --list-formats-ext -d /dev/video_X_   
   ```
   Please, send me the output you obtained.
3. Now, we will check if ffmpeg records a video properly using your capture card. Run the following command replacing, again, the _X_ by the number of your device:
   ```
   ffmpeg -f v4l2 -i /dev/video_X_ -t 10 video.mp4
   ```
   Does the video show a blue screen?

**Comment by RandomizerGamerRIPLinky** [comment]
It's giving me this error on the first step.

E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 14116 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

**Comment by Dinones** [comment]
Please, fully restart your VM and try again. Does the error solve?

**Comment by RandomizerGamerRIPLinky** [comment]
After trying the 2nd step, it gave me the option to install the base packages so after that installed I was able to successfully complete step 1

**Comment by RandomizerGamerRIPLinky** [comment]
2nd step provides no results in video devices

**Comment by RandomizerGamerRIPLinky** [comment]
vboxuser@Shiny-Hunt-Automation:~/Desktop$ v4l2-ctl --list-devices
Cannot open device /dev/video0, exiting.
vboxuser@Shiny-Hunt-Automation:~/Desktop$

**Comment by Dinones** [comment]
Can you tell me exactly what capture card you are using (the complete name)? Is it compatible with Linux?

**Comment by RandomizerGamerRIPLinky** [comment]
I included the Elgato HD60 in the title, as that's the card I'm using. Technically, no elgato product is supposed to be compatible with Linux

**Comment by Dinones** [comment]
Can you please open a terminal and run `lsusb`? You should see the Elgato HD60 listed. If it’s not listed, the issue might be with the host system or the device itself.

**Comment by RandomizerGamerRIPLinky** [comment]
How would I open up lsusb?

**Comment by Dinones** [comment]
You have to open a terminal and write `lsusb`. This command will list all the usb devices connected to your VM.

**Comment by RandomizerGamerRIPLinky** [comment]
Ok. It shows my logitech camera that I just got out of storage, and it's actually showing up but now it's stuck on Wait_Pairing_Screen

**Comment by RandomizerGamerRIPLinky** [comment]
It's now back to doing its restart loop

**Comment by RandomizerGamerRIPLinky** [comment]
Is it Iusb or lusb (i or lowercase L)

**Comment by RandomizerGamerRIPLinky** [comment]
lusb isn't on my vm, which is odd since I followed the directions to a T

**Comment by Dinones** [comment]
Let's go one by one:

> Ok. It shows my logitech camera that I just got out of storage, and it's actually showing up but now it's stuck on Wait_Pairing_Screen

Does this device solve the blue screen error then? It may be that some drivers are not installed on the Elgato capture card.

> It's now back to doing its restart loop

By the restart loop, you mean it constantly restarts the game when in the state `RESTART_GAME_1`?

> Is it Iusb or lusb (i or lowercase L)

It is `lsusb`; you are skipping an s.

**Comment by RandomizerGamerRIPLinky** [comment]
Ah, ok thank you for the lsusb. I didn't read it, that's on me. The logitech camera shows up in the fb shiny hunter app now, but it is still having the error of constantly restarting. It is still in restart game 1.

**Comment by RandomizerGamerRIPLinky** [comment]
The elgato shows up in lsusb

**Comment by Dinones** [comment]
> Ah, ok thank you for the lsusb. I didn't read it, that's on me. The logitech camera shows up in the fb shiny hunter app now, but it is still having the error of constantly restarting. It is still in restart game 1.

Let's solve the `RESTART_GAME_1` issue first. In order to download the latest version, you can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

**Comment by RandomizerGamerRIPLinky** [comment]
I did that and it's still giving me the Restart_Game_1

**Comment by Dinones** [comment]
In that case, could you please follow these instructions: https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781 and tell me the result?

**Comment by RandomizerGamerRIPLinky** [comment]
It gives me: Could not access video capture '0'

**Comment by RandomizerGamerRIPLinky** [comment]
the elgato driver is an exe, so I'm not sure it'll work

**Comment by RandomizerGamerRIPLinky** [comment]
And I'm broke so I can't buy another capture card

**Comment by Dinones** [comment]
You encounter this issue while using the Elgato capture card, right? Didn't you say you had a Logitech capture card?

**Comment by RandomizerGamerRIPLinky** [comment]
While using my elgato, yes I have the issue. I have a logitech webcam (not a capture card) that I tried using but it's blurry so I don't know what to do.

**Comment by RandomizerGamerRIPLinky** [comment]
I will give that a try, but it looks very confusing to me

**Comment by Dinones** [comment]
This may help you: https://chatgpt.com/share/00836774-01f0-445d-8f68-b6f79e5b4fc3

**Comment by RandomizerGamerRIPLinky** [comment]
Thank you! Please bear with me, I'm not too familiar with some of the things I'm doing so it's all brand new to me and I'm trying to learn as I go along.

**Comment by Dinones** [comment]
Don't worry! Everyone had to learn some time. Let me know if you need some help. And remember, you can also contact me on Discord.

**Comment by RandomizerGamerRIPLinky** [comment]
Ok! Thank you so much! I'll try to find your discord real quick so I can chat with ya on there

**Comment by RandomizerGamerRIPLinky** [comment]
vboxuser@Shiny-Hunt-Automation:~/Desktop/elgato-gchd/build$ sudo ./src/gchd
The Elgato Game Capture HD60 is currently not supported.
vboxuser@Shiny-Hunt-Automation:~/Desktop/elgato-gchd/build$ 
welp, this sucks.... is there a way I could make it work off of my webcam instead?

**Comment by RandomizerGamerRIPLinky** [comment]
I was able to do everything right, but my capture card just isn't supported by this

**Comment by RandomizerGamerRIPLinky** [comment]
I don't think I'll be able to use my elgato hd60 at all with this, sadly. Unless there's a way I could make the logitech Camara work

**Comment by Dinones** [comment]
That's what I was thinking about. I'm sorry to hear that. I bought [the cheapest capture card I could find on Amazon](https://www.amazon.es/Capturadora-capturadora-Transmisi%C3%B3n-Ense%C3%B1anza-Videoconferencia/dp/B0B7DSPPNX/ref=sr_1_3?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=19AXJAEC6F2GB&dib=eyJ2IjoiMSJ9.EQaQ5oiRaR3x51A0oHyllF9YLPjzGEAdQKOFeFHuno_VHUCBn8iKjtsHGAkU4WRYxTct-2UNP4yJeR3QXTQbIIqTP1Uh3nsLEdegtfOdFY1kX3cZp0h-lYVKglXvMk3TwuAh0go2CXT8hYZseHcBFncyWXbq-PpHBDG_nQUuLipMSBjV-nx9k9VC5nd-gR4Kohtn9CPLRtLTIjeTX7bqA2448zpfRmQvFUuraeEndRylTrbhMCrZh3d4OTEqi8YWYs-AMNb3gRAMrbOyOLKehbTVYzNFd54P3w3WqX5WSHE.jER3RZN5EhgO-HfHZRu6ps4R7c1c_cUd363FsgXdUhQ&dib_tag=se&keywords=capture+card&qid=1724274468&refinements=p_36%3A-1100&rnid=1323854031&s=electronics&sprefix=capture+card+%2Celectronics%2C109&sr=1-3) for about 8.5€, which was this one:

![image](https://github.com/user-attachments/assets/cd7a7e49-35ec-4a76-87cf-3acebc68bc78)

**Comment by RandomizerGamerRIPLinky** [comment]
I'll have to see if I can convince my family to help me get that lol
