### ISSUE TITLE
Home on loop

### ISSUE THREAD

**Issue by Xion3582** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#14]
Hello, I fixed my previous issue (it fixed by itself)

However, now, I select static encounter, it automatically goes into 'RESTART_GAME_1' after pairing,  my game is at 30 fps, screen is at 100%, menu is in light color

**Comment by Xion3582** [comment]
So basically, it restarts the game, goes into the game again, but since there is the into of the game, it doesn't wait enough time and goes back to home to restart game

**Comment by Dinones** [comment]
Can you please provide me with a short video showing what is exactly happening?

**Comment by Xion3582** [comment]
https://github.com/user-attachments/assets/a0c2e250-06c6-48c5-aa1b-2d5366bd2792

here it is

**Comment by Dinones** [comment]
You are having the same issue as https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11.
