### ISSUE TITLE
Using webcam instead of capture card

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#17]
The application recognized the new webcam, and actually went into the save but now it's not letting it have enough time to get into the file before doing Restart_Game_1 then when it goes into the game it skips the rest of the restarts and goes immediately to Enter_Lake_1

**Comment by RandomizerGamerRIPLinky** [comment]
Yes, and I have blocked off all light but it's having an issue with the text boxes now. I see the purple line, but it doesn't seem to be working. I did manage to get it to select Piplup earlier though, so it's definitely worth noting

**Comment by Dinones** [comment]
There's no way that webcap setup could work. Can you please send me a picture of the setup and what is the camera recording?

**Comment by RandomizerGamerRIPLinky** [comment]
I have it boxed off, so I won't be able to take a photo of it (It's pretty ugly as I had to make something quick to test it out as I was curious if it would work and it seems to work for the most part)

**Comment by RandomizerGamerRIPLinky** [comment]
I think I may need to turn the brightness down a tad

**Comment by RandomizerGamerRIPLinky** [comment]
It's sadly recording the screen of my switch, but I was really curious and as mentioned earlier, I was able to get it to choose piplup so I do think it can work

**Comment by RandomizerGamerRIPLinky** [comment]
It is consistently going up to starter_selection_1 before reseting, so it's definitely possible

**Comment by RandomizerGamerRIPLinky** [comment]
Where does the purple line have to line up on Starter_Select_1?

**Comment by RandomizerGamerRIPLinky** [comment]
![17243606380914085330084788329601](https://github.com/user-attachments/assets/e939d47b-2c02-43bd-ab2f-668bad9ebf42)

Here's what it looks like without the box

**Comment by RandomizerGamerRIPLinky** [comment]
But without the box, it is a bit difficult to get consistent results

**Comment by RandomizerGamerRIPLinky** [comment]
I think it may be the color

**Comment by RandomizerGamerRIPLinky** [comment]
Is there a way to widen the range just a bit? If so, how would I go about that? I do want to see if I can get it to fully work, as it would help out a lot more people who don't have capture cards

**Comment by Dinones** [comment]
I do not really think it will work, but if you want to try, the larger purple line must get the test box white background as for the image, and the smallest one must check the white color of the pokémon life box, on the left of the life bar.

![image](https://github.com/user-attachments/assets/86e698c1-245a-4468-a4f3-f71dd7106dfb)

> https://youtu.be/1BHVRWNQ_Gs

By the way, the video cannot be seen _(it's published in private)_.

**Comment by RandomizerGamerRIPLinky** [comment]
Ok! Thank you, I'll give it a shot!

**Comment by RandomizerGamerRIPLinky** [comment]
So far it has recognized 2 non shinies

**Comment by Dinones** [comment]
Wow, I'm really interested in seeing the video it records. Could you please upload the video it saves for every encounter? It is located in the `Media/Videos/` folder.

**Comment by RandomizerGamerRIPLinky** [comment]
When I tried stopping the terminal before it started a new restart, it wasn't able to keep the videos. It only has the one that is 2 seconds long of it just barely getting to the game. I will try to get it to happen again, but I do think it is a part of the webcam as it keeps correcting the brightness and even full brightness on my switch provides inconsistent results.

**Comment by RandomizerGamerRIPLinky** [comment]
Do you know of a way around that by chance?

**Comment by Dinones** [comment]
Just stop the program when you enter the combat before it restarts the game.

**Comment by RandomizerGamerRIPLinky** [comment]
Ok! I'm still having a bit of a hard time getting it to fully work (I had to make the screen black due to the auto exposure and I'm not sure how to get rid of that)

**Comment by RandomizerGamerRIPLinky** [comment]
Might try it on the big screen again soon

**Comment by RandomizerGamerRIPLinky** [comment]
https://youtu.be/Zn5r5px15J0
Here's the latest one I was able to get.

**Comment by RandomizerGamerRIPLinky** [comment]
It's still processing as  I'm on the VM trying to get it done.

**Comment by RandomizerGamerRIPLinky** [comment]
I can confirm that the color for mine needs to be updated, however I am unsure of how to do it. I found out where it is in the scripts, but I don't really know how to change it so that it runs it fully.

**Comment by RandomizerGamerRIPLinky** [comment]
You can see that I had to force the black onto the screen so that it could detect the white, which is due to the auto exposure built into the webcam.

**Comment by RandomizerGamerRIPLinky** [comment]
217,187,216 for starter select 1 and 2 before it asks you if you want the pokemon, then 217,187,216 for when it asks you if you want it

**Comment by RandomizerGamerRIPLinky** [comment]
That's the RGB for it at least and it would also apply to the battle as well but I'll double check those

**Comment by RandomizerGamerRIPLinky** [comment]
Glad I checked. The RGB values for the battle and Piplup's health are as follows:  145,130,150 244,226,238 and 216,214,228

**Comment by RandomizerGamerRIPLinky** [comment]
Not sure if It'll help, as I'm not sure how that relates to python coding but hopefully it helps some

**Comment by RandomizerGamerRIPLinky** [comment]
Nvm, just got it working so I'm going to go ahead and close it. It required very fine tuning of the brightness and a terminal prompt to get rid of the webcams built in features while it's running. I'll post the shiny once I get it!

**Comment by RandomizerGamerRIPLinky** [comment]
Nvm, just got it working so I'm going to go ahead and close it. It required very fine tuning of the brightness and a terminal prompt to get rid of the webcams built in features while it's running. I'll post the shiny once I get it!

**Comment by Dinones** [comment]
No way this worked! OMG jajajaja
