### ISSUE TITLE
Program crashes due to missing Constants attribute & controller state doesn't trigger restart

### ISSUE THREAD

**Issue by LostTambo** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#2]
Ran into a couple of issue when first attempting to run this on the Raspberry Pi 4. The program launches and NBXT interacts with the game however once it enters the main loop and detects that it isn't the shiny version the program crashes stating the following:
`Traceback (most recent call last):
  File "/home/{user}/Desktop/Nintendo-Switch-Pokemon-Shiny-Hunter/Shiny_Hunter.py", line 104, in <module>
    if attempts - initial_attempts >= CONST.AUTORESTART_ATTEMPTS: 
AttributeError: module 'Constants' has no attribute 'AUTORESTART_ATTEMPTS'`

Adding `AUTORESTART_ATTEMPTS = 0 ` to `Constants.py` seems to progress the program, however the system isn't restarted as 
`Switch_Controller.current_event` is set to `HOME_RESTART_SYSTEM`. Setting this value to something higher (100000) opens and closes the home screen repetitively and the `Switch_Controller.current_event` is set to `HOME_RESTART`.

Having `AUTORESTART_ATTEMPTS = 0 ` in Constants.py and changing the `elif self.current_event in ['HOME_STOP', 'HOME_RESTART]'` block within `Switch_Controller.py` to:
`elif self.current_event in ['HOME_STOP', 'HOME_RESTART', 'HOME_RESTART_SYSTEM']:`
`if self.current_event == 'HOME_STOP': sleep(CONST.SHINY_RECORDING_SECONDS)`
`home_macro(self.nxbt_manager, self.controller_index)`
`if self.current_event == 'HOME_STOP': self.current_event = 'WAIT_HOME_STOP'`
`elif self.current_event == 'HOME_RESTART': self.current_event = 'WAIT_HOME_RESTART'`
`elif self.current_event == 'HOME_RESTART_SYSTEM': self.current_event = 'RESTART'` 

Restarts the game and moves through the progress of increasing the attempt counts etc.

**Comment by Dinones** [comment]
That constant was something I was testing, it seems I did not delete all the related code. Just give a high value like you said 100000. It will be solved in the next update. Refering to the repetitively open/close of the home screen, it may be that you're not using the default white mode of the nintendo, or that you're using a custom wallpaper (the backgorund must be the default white one). The program checks if the nintendo is in the home screen before restarting to avoid breaking itself. It will also be solved in the next update and noted in the ReadMe, which I'm working on to make it more undestandable.

**Comment by LostTambo** [comment]
Thanks for that, I have added the value to be 10000, and changed the switches wallpaper back to the default white (was set to the default dark wallpaper) and that has done the trick.
