### ISSUE TITLE
Turtwig instead of Chimchar when resetting for Starters

### ISSUE THREAD

**Issue by MCPika** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#22]
Good afternoon,

I'm resetting for chimchar and this is not the first time catching an image of a turtwig popping from time to time instead of resetting only for chimchar xd
As you can see the Database have caught up to those shenanigans and apparently the program went for turtwig as i supsected 9 times out of the 2814 resets for chimchar only (center pokemon)
![image](https://github.com/user-attachments/assets/f86c05c5-1ac5-43ba-95ec-cf0760994566)

There's the sneaky fella, So I was wandering what could be causing that? Maybe give the command more time when selecting the pokemon or maybe the solution would be to have B press button just in case when the mallet opens?
![image](https://github.com/user-attachments/assets/c595453f-0fd5-403d-a3f9-96c519abf5d9)

And as I type this issue I'm wandering if this is randomn or does this happen everytime the game possibly gives away a shiny Chimchar but that seems to be pushing it a bit far haha

**Comment by RandomizerGamerRIPLinky** [comment]
I have the same thing, but with the starter I'm going for, it's the Penguin

**Comment by Dinones** [comment]
Hi guys! I'll explain to you what's happening. From time to time, some button presses are not detected by the Nintendo, so when pressing right/left to select Chimchar/Piplup, the action is not performed. This is a small issue that only happens with the starters, as I cannot press multiple times the right/left buttons because it has to be pressed exactly once.

It sometimes happens to me, but my ratio is about 1/1000 Turtwigs. Can you confirm what's more or less the ratio for you?

If it's not happening a lot, I'm not solving it, as it'd be a bit complex to detect the button press and does not affect a lot (the probability of you finding a shiny Turtwig instead of the Chimchar/Piplup is really low).

**Comment by Dinones** [comment]
> And as I type this issue I'm wandering if this is randomn or does this happen everytime the game possibly gives away a shiny Chimchar but that seems to be pushing it a bit far haha

Regarding this, the worst situation you can encounter is that you find a shiny Turtwig instead of the Chimchar/Piplup, which is not that bad at all and not really likely to happen.

**Comment by MCPika** [comment]
> Hi guys! I'll explain to you what's happening. From time to time, some button presses are not detected by the Nintendo, so when pressing right/left to select Chimchar/Piplup, the action is not performed. This is a small issue that only happens with the starters, as I cannot press multiple times the right/left buttons because it has to be pressed exactly once.
> 
> It sometimes happens to me, but my ratio is about 1/1000 Turtwigs. Can you confirm what's more or less the ratio for you?
> 
> If it's not happening a lot, I'm not solving it, as it'd be a bit complex to detect the button press and does not affect a lot (the probability of you finding a shiny Turtwig instead of the Chimchar/Piplup is really low).

![image](https://github.com/user-attachments/assets/b5daca27-b712-466b-92e9-9157957b2391)

As of right now my odds are 1/200ish but ill keep resetting until chimchar shinny gets around and see the odds by the end of time . If I cumulate the odds with the ones above meaning around 4000 resets and making the odds at 14/4000ish

**Comment by Dinones** [comment]
That's more or less the odds I'd expect. As said, it is very rare for you to find a shiny Turtwig when trying to find another starter, and since the solution would imply an increase of the global time, and thus, a downgrade of the overall efficiency, I will not upload a solution.
