### ISSUE TITLE
Application freezes after 1000 resets

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#23]
So I've noticed that right around or just after 1k resets that it will freeze up and the capture card needs to be unplugged and plugged back in for it to work again (went through GUI.py to test it out). At random, it will detect a false shiny Starly for the starter sequence and wouldn't detect the Shiny Starly that was unobtainable (probably a good thing, but I still wanted the video)

**Comment by Dinones** [comment]
Thank you for reporting! Here's what's happening:

1. It sometimes (very very rarely) detects the Starly as the starter, and the detection time will always raise a false positive shiny due to the time between the text boxes of _"A Starly appeared!"_ and _"Go, Chimchar/Piplup/Turtwig!"_. I have pushed a new version that solves this. You can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

2. Can you explain me a little bit more about the freeze issue with the capture card? What do you mean exactly with _"it freezes"_?

**Comment by RandomizerGamerRIPLinky** [comment]
Thank you! So the application itself stops working, no more inputs are made and is frozen but the video still works

**Comment by RandomizerGamerRIPLinky** [comment]
It just hit 1003 encounters on the wild Pokémon, going to see if it continues or if it still has the same issue

**Comment by Dinones** [comment]
Does the freeze happen always when you reach the +1000 encounters, or was it just one or two times?


I cannot replicate the issue in my computer, as for me I made it work for more than 48h in a row without encountering any problem.


1. Can you tell me the capture card you are using? 
2. If it happens again? Is the capture card at an abnormally high temperature?

**Comment by RandomizerGamerRIPLinky** [comment]
That's odd, yeah it does stop working properly after about 1200 resets or encounters and I have to restart the whole terminal. It has detected 5 false shinies in a row, so I'm not really sure what's going on. I'm using a Razer Ripsaw HD Capture Card

**Comment by RandomizerGamerRIPLinky** [comment]
It also seems to give false positives during certain parts of the day when the colors change ever so slightly to match the time of day in real life

**Comment by RandomizerGamerRIPLinky** [comment]
But only during those parts of the day

**Comment by RandomizerGamerRIPLinky** [comment]
I'm unable to get any of the false shinies at this moment, which is honestly a good thing as it means it may have been fixed

**Comment by RandomizerGamerRIPLinky** [comment]
It gave another false positive shiny, and it's not letting me send the video as it's too large and I don't have a video trimmer

**Comment by RandomizerGamerRIPLinky** [comment]
It always seems to give false positives on the morning cycle where the colors are ever so slightly different

**Comment by RandomizerGamerRIPLinky** [comment]
I forgot to answer a previous question you had asked; the capture card is room temp and doesn't show any signs of heat

**Comment by Dinones** [comment]
Hi! Sorry for the late response—I was away on a business trip.

> It always seems to give false positives on the morning cycle where the colors are ever so slightly different

It might just be a coincidence. Could you confirm if this always happens during the day cycle change, or does it also occur at other times? Also, what FPS are you getting when running the Shiny Hunter?

**Comment by RandomizerGamerRIPLinky** [comment]
You're all good! It does happen during the day cycle change, it hasn't really occurred at other times and I'm getting 30+ fps on the Shiny Hunter

**Comment by Dinones** [comment]
The day cycle should not affect the program, as it detects specific pixels that are not impacted by it, such as the text box or the black load screen.

Could you please try to execute the Shiny Hunter at different times of the day?

- Morning — 4:00 a.m. to 9:59 a.m. 
- Daytime — 10:00 a.m to 7:59 p.m.
- Nighttime — 8:00 p.m. to 3:59 a.m. 

When does the error occur?

**Comment by RandomizerGamerRIPLinky** [comment]
Morning cycle gives the false positive

**Comment by Dinones** [comment]
Okay, thank you! Does it always happen during the morning cycle, or does it only occur when changing from night to morning?

**Comment by RandomizerGamerRIPLinky** [comment]
Both, actually

**Comment by Dinones** [comment]
Hmm can you please send me the video you get?

**Comment by Dinones** [comment]
@RandomizerGamerRIPLinky not answering, issue closed as **invalid**.
