### ISSUE TITLE
Wild encounters stuck on "ESCAPE_COMBAT_1" state

### ISSUE THREAD

**Issue by RandomizerGamerRIPLinky** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#24]
It won't get past the loading screen for the game, not sure what's going on. Will record in the am as it's almost midnight as I'm writing this out. It gets stuck after choosing the game and then just restarts, making an endless loop

**Comment by RandomizerGamerRIPLinky** [comment]
After doing the git pull origin master command, it now goes into the battle but it still won't run from the battle and resets the game

**Comment by RandomizerGamerRIPLinky** [comment]
https://youtu.be/gCq4EJ2Hq24

**Comment by Dinones** [comment]
Hmm, it seems it's not detecting the correct white color to change from the `ESCAPE_COMBAT_1` to the `ESCAPE_COMBAT_2`. Could you please follow [these steps](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781) and tell me the output you get?

**Comment by RandomizerGamerRIPLinky** [comment]
oddly enough, all of them are 250,250,250 except for when the Pokemon is thrown out, which gives a 244,244,244

**Comment by RandomizerGamerRIPLinky** [comment]
![12](https://github.com/user-attachments/assets/3ce239c4-76e9-41ab-be1c-fe0badb6c72f)
![1725123053 3560438](https://github.com/user-attachments/assets/bc660b30-4af0-4d9e-942d-bf944705a43b)
![1725123055 665798](https://github.com/user-attachments/assets/dbefac06-15b7-465b-95e4-520f34cbd187)

**Comment by RandomizerGamerRIPLinky** [comment]
So on the last photo that was sent, it shows 244,244,244

**Comment by Dinones** [comment]
I have pushed a new version that solves this. You can either clone the repository again git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git or update the current one git pull origin master in your local repository folder.

Can you please confirm if the issue has been solved?

**Comment by RandomizerGamerRIPLinky** [comment]
Thank you so much! It works now!
