### ISSUE TITLE
Bluetooth Adapter Compatibility Issues

### ISSUE THREAD

**Issue by MMartin1211** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#26]
When installing the program following the instructions as written I was encountering issues getting the Bluetooth working. After a good deal of troubleshooting I discovered that the Bluetooth adapter I have is not compatible with the recommended version of XUbuntu (22.04.3). The adapter is the TP-Link UB500 Nano USB Adapter, which according to my research is only compatible with Linux kernel 5.16 and above, while XUbuntu 22.04.3 uses kernel 5.15.

I created a new VM using a newer build of Ubuntu (version 24.10, found here: https://cdimage.ubuntu.com/daily-live/current/), and encountered issues with installation of "Requirements.txt". Attempting to install returns an error stating "This environment is externally managed" and suggests using "sudo apt install _name of Python package_" instead. Using the recommended code for each package within the Requirements.txt file returns "Error: Unable to locate package".

I am a novice at using Linux so it is very likely I am doing something wrong, but any help you can provide is greatly appreciated.

**Comment by Dinones** [comment]
Hi! Thank you for reporting and for the info you provided. Please, try running:

```
sudo apt update
sudo apt install python3-pip
```

Now, try if any of these methods work for you:

# Method 1
```
sudo pip install --user -r Requirements.txt && pip install --user -r Requirements.txt 
```
```
export PATH=$PATH:~/.local/bin
echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
source ~/.bashrc
```

# Method 2
```
sudo pip install --break-system-packages -r Requirements.txt && pip install --break-system-packages -r Requirements.txt
```

# Method 3:
```
sudo pip install --upgrade pip
sudo pip install -r Requirements.txt && pip install -r Requirements.txt 
```

**Comment by trungnt92** [comment]
I got the same issue.

Tried the Method 1 and Method 3 will give this 
`error: externally-managed-environment`

Tried the Method 2 and got this
```
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement numpy==1.21.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0rc1, 1.25.0, 1.25.1, 1.25.2, 1.26.0b1, 1.26.0rc1, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 2.0.0b1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0)
```

Maybe can you upgrade the version of numpy to allow newer version of python?

**Comment by Dinones** [comment]
Could you please tell me exactly the Linux distribution you are using and its version (if you have the link, it would help too). I'll install your VM distribution and work on it.

**Comment by SNIELSEL** [comment]
i had the same iisue first and this is what enabled bluetooth for me on ubuntu 20.04 on physicall hardware instead of vm.
this should also work on vm but its at least worth a try. 

1. run these 2 commands
`wget https://raw.githubusercontent.com/Realtek-OpenSource/android_hardware_realtek/rtk1395/bt/rtkbt/Firmware/BT/rtl8761b_config`
`wget https://raw.githubusercontent.com/Realtek-
OpenSource/android_hardware_realtek/rtk1395/bt/rtkbt/Firmware/BT/rtl8761b_fw`

2. Move the files to the /lib/firmware/rtl_bt directory:
`sudo mv rtl8761b_config /lib/firmware/rtl_bt/rtl8761b_config.bin`
`sudo mv rtl8761b_fw /lib/firmware/rtl_bt/rtl8761b_fw.bin`

3. Rename the rtl8761b driver to rtl8761bu:
`sudo cp /lib/firmware/rtl_bt/rtl8761b_config.bin /lib/firmware/rtl_bt/rtl8761bu_config.bin`
`sudo cp /lib/firmware/rtl_bt/rtl8761b_fw.bin /lib/firmware/rtl_bt/rtl8761bu_fw.bin`

4. Reboot

the reason for this is because the they changed the name for the bin file its looking for on Linux kernel 5.15

answer found in this post: https://askubuntu.com/questions/1256245/bluetooth-5-0-in-ubuntu-20-04

**Comment by MMartin1211** [comment]
I tried Methods 1-3 above and got the same results trungnt92 reported. I will need to reinstall the older version of Ubuntu to try SNIELSEL's solution, so I will reinstall it and give it a shot. I'll report my results here when done.

**Comment by trungnt92** [comment]
> Could you please tell me exactly the Linux distribution you are using and its version (if you have the link, it would help too). I'll install your VM distribution and work on it.

I am using this one [Xubuntu 24.04](https://torrent.ubuntu.com/xubuntu/releases/noble/release/desktop/xubuntu-24.04.1-desktop-amd64.iso.torrent) 

About SNIELSEL's solution, actually, i have tried some other solution including add firmware/update kernel, etc ... and the system can recognize the bluetooth adapter even with Xubuntu 22.04. But the problem come later when the bluetooth keep disconnect the switch after sometime running the program normally, sometime it is 30 mins or sometime it is 5 mins and i cannot leave it running too long. So i want to try another newer version of Xubuntu where the bluetooth work out of the box, with 24.04 the adapter showing without do anything like... but then the python not work.

**Comment by Dinones** [comment]
Hi! Sorry for the late response—I was away on a business trip. Could you please let me know where you are currently at so I can assist you further?

**Comment by MMartin1211** [comment]
Currently I have 2 VMs set up through VirtualBox, one running Xubuntu 20.04.6 and the other running Ubuntu 24.10. On 20.04.6 I have successfully installed all of the programs and have confirmed that the Bluetooth adapter can be seen by the VM, but when testing the NXBT application a pairing request is never initiated. A program gui appears for a few seconds then closes without doing anything. The terminal gives a message saying the Bluetooth has been restarted but nothing else happens.

On the VM with Ubuntu 24.10 I am unable to install Requirements.txt. I either get an "Externally Managed Environment" error, or an "unable to locate package" error.

**Comment by trungnt92** [comment]
@MMartin1211 for VM Xubuntu 20.04.6 you can try update the kernel only with https://askubuntu.com/questions/860695/how-to-upgrade-just-the-kernel or search around about kernel update. I had successfully connected and run the bluetooth adapter/program after try around with the kernel update only, but in my case the bluetooth connection not running too long and auto disconnect after sometime ... that's why i tried 24.04. Maybe you can have a different result than me.

**Comment by MMartin1211** [comment]
@trungnt92 Unfortunately that didn't work. I keep getting an unspecified error when it tries updating the kernel.

**Comment by chaosfreakx** [comment]
@MMartin1211 i had bluetooth issues with my laptop , the gui would load then stop exit and release 3 or 4 threads , what worked for me was @SNIELSEL s method followed by sudo reboot now then turn off your bluetooth with the icon in taskbar , then run python3 Shiny_Hunter.py and boom working blueetooth,

**Comment by chaosfreakx** [comment]
@MMartin1211 can you confirm if turning off the bluetooth fixed the program closing when trying to connect to bluetooth ?

**Comment by Beanh0le** [comment]
I bought the same wireless adapter from amazon for this and was having the same problems. 
The solution @chaosfreakx posted worked for me on Xubuntu 20.04.6

**Comment by chaosfreakx** [comment]
Thankyou for testing and getting back , im very glad my solution worked !!!! , i have tested long periods and no connection issues ,

**Comment by MMartin1211** [comment]
@chaosfreakx OMG, thank you! This worked! I've been trying to figure this out for weeks, but it's working now! As Beanh0le said, I haven't tested if it stays connected for extended periods, but it at least paired!
