### ISSUE TITLE
Capture card not compatible

### ISSUE THREAD

**Issue by tmlkarma** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#32]
![Capture d'écran 2024-09-09 001207](https://github.com/user-attachments/assets/095c1a70-819d-4e08-a71c-bc3fbd5e83b2)
I've just installed a VM and followed all the instructions all's working the only problem is that the program isn't starting 
the bluetooth programed controller is connnecting but after ut appears in the menu nothings happen it's stays in the menu 
Maybe i missed somthing
 is it normal that the screen is black in the program same as the controller place
My capture card is detected and set as ok when i test it btw 
Thanks for helping me

**Comment by Dinones** [comment]
Hi! Could you please answer the following questions:

1. Did all the installation verifications work?2. What program are you executing when you get the image you sent?
3. Is your main issue that when running the `Shiny_Hunter.py` script, the controller connects but does nothing?

Based on the information you provided, I don’t see the connection between the black screen and the controller. Answering these questions will help me understand the problem better.

**Comment by tmlkarma** [comment]
1. Did yes execpt the video capture it says okay but when i try to take a screenshoot  it doesn't work i remarked that my capture card is turning off after few seconds it's an avermedia and i can't find the driver for it in the right kernel version so i'll buy a little 7 euros card that should work 
2. shiny hunter static but itested it's the same for all of them
3. yes it's stay connectd but do not act

**Comment by Dinones** [comment]
Thank you for your response! Let's address each point one by one:

1. If the capture card stops after a few seconds, it might not be compatible with Linux. You can look up the exact model of your capture card online to check its compatibility.
2. It doesn't initialize because the capture card is not receiving any image.
3. How do you know it connects if the screen is black? I assume you disconnect it from the dock station; if that's the case, the problem is likely related to the capture card again. It won't start doing anything until it detects the pairing screen.

**Comment by tmlkarma** [comment]
1 i bought one on amazon for 7 euros i recieve it tommorow 
3 my capture card as an in and out hdmi so i can link in it on my room tv while launching de program

**Comment by tmlkarma** [comment]
i recieved my new capture  card and now the controller is acting a bit but i got a problem with the image 
![Capture d'écran 2024-09-11 202326](https://github.com/user-attachments/assets/12415879-f760-4579-a470-6216d20a7615)

**Comment by Dinones** [comment]
Hi! I'm happy to hear it's working now! So, the issue is solved, right?

> for the github page i think maybe you can add when you explain how to add usb in the vm to choose the right option it could maybe prevent some issues

What do you mean by this? Do you mean selecting USB 3.0 instead of USB 2.0?

**Comment by Dinones** [comment]
Perfect! Thank you for the information about USB. I'll add a comment in the instructions (all my ports are 3.0, so I wasn't aware of this).
