### ISSUE TITLE
Crash for Palkia shiny hunt

### ISSUE THREAD

**Issue by David34920** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#34]
The app crash for Palkia shiny hunt.
We enter in CHECK_SHINY too early and the app fail to recognize the pokemon name since we are still in the start animation.
Exception in pokemon_image.recognize_pokemon()

It appears that the delay of 2 seconds is not enough for Palkia fights (I assume it's the same for Dialga).
The white screen make more than 2 seconds to appears.
With a delay of 4 or 5 seconds the app does not crash anymore and look like it's working (currently hunting).

I made a pull request to allow to configure the delay

**Comment by Dinones** [comment]
Hi David, Thank you! I have merged your pull request (https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/commit/a71f6dc4dfe6474c67fe965c3e010825db0faa24). I anticipated this might happen, but I couldn't test it as I was not able to catch another Dialga/Palkia at the moment.

**Comment by David34920** [comment]
I will check all the legendary, but it will require some time...
