### ISSUE TITLE
Stuck in "Change Grip/Order" menu 

### ISSUE THREAD

**Issue by monkeybee11** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#4]
with you saying some bugs are related to the raspberry pi4 @Dinones  in the other issue me posted #1 
me thort ill try installing ubuntu on WSL (turns out WSL dosnt suport bluetooth >.>)
so setted up ubuntu on a virtualbox VM and spent today trying to get every thing setted up and now the program just dosnt do anything after the controller has conected 🤔 

![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/520f5633-2c12-4586-9c3e-ddfa477a4300)

did a quick print(1) debug in Shiny_Hunt.py it never got to print(3)
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/5f0258d8-62b2-4e23-9a5e-c53f4116aae3)
(sorry for the screenshot im having troble getting copy paste to work to and from the VM >.>)

**Comment by Dinones** [comment]
I see, so with the Raspberry the controller works, but it doesn't with the VM? Does it connects and then disconnects or gets stuck automatically when connecting? I'm writting instructions to setup exactly the same VM I use. On the other hand, I do not get any of these WARNINGS. Try downloading the latest version `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` of the program.

**Comment by monkeybee11** [comment]
ill give it a shot but errr a bit random sometimes the controller conects on 1st try others it shows paring in the top connor 2-3 times before it shows up in the player 1 slot (going to try fresh download BTW is the AUTOATTEMPT=1000 thing fixed?

**Comment by Dinones** [comment]
> ill give it a shot but errr a bit random sometimes the controller conects on 1st try others it shows paring in the top connor 2-3 times before it shows up in the player 1 slot (going to try fresh download BTW is the AUTOATTEMPT=1000 thing fixed?

It sometimes happens that the controller seems to connect and then disconnects, just keep waiting. Restarting the VM can help. Depending on the OS you downloaded, it may open a bluetooth connection confirmation box you should click on.
The latest version should have solved the constant error too.

**Comment by monkeybee11** [comment]
it shows up with that window on my pi not this ubuntu thing ive setted up >.> im new to linix so just fallowed a random tutoral online

still no luck shows up with the same stuff 

![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/1bf87870-490c-49c7-8488-ab4d51441239)

ill try the newest verion on my pi see if it gets past the 1st battle if theres any info me can give from the virtualbox VM let me know :)

**Comment by monkeybee11** [comment]
![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/0dfe7c83-9664-4460-9c60-709ba5b733a6)


ok so even on the pi it stops at the same place with the newest verion of the code 🤔 thats not right

**Comment by Dinones** [comment]
After some debugging, the shiny hunter was entering an state that belonged to wild hunter. I've just uploaded the latest version.

**Comment by monkeybee11** [comment]
it seems to be working on my pi now so thats good :o  it dose press home and jumps between game and home a few times before it presses X to cansel the game now 

![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/cf6f909d-98b8-4c12-a605-2e937c81359e)


huh dont know if it was bc me was playing around with the CMD and covered up the programs window to take that screen shot but it kinda messed up after taking the screen shot and attacked shaymin and now stuck in the battle screen agen (im gonna try restarting it)

heres a pastebin to the CMD log https://pastebin.com/pu5DQBU2

**Comment by Dinones** [comment]
Can you tell me what Raspberry Pi do you have? I've been testing with a Raspi 4 Model B. As I can see in the pastebin, it keeps toggling from the game screen to the home screen constantly... This may be due to the capture card does not process images very fast, you can try increasing the time the program has to wait before checking if it's in the home screen. In `/Utils/Macros.py`, change this line `__test_print_command(MSG.WAITING_SECONDS.replace('{seconds}', str(1))); sleep(1)` of the `home_macro()` to `__test_print_command(MSG.WAITING_SECONDS.replace('{seconds}', str(2))); sleep(2)`, if it's not enough, increase more the time.

**Comment by monkeybee11** [comment]
im using that same pi the pi4 model b

it is running my discord bot at the same time so mite be the problem
ill try it with out the bot running tomreooh then with thos changes you said

......in till me started typing this it was working fine on the ubuntu VM but pokemonBD just crashed XD

![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/1711586/321985ef-65da-43a5-8b98-70c435e063da)

**Comment by Dinones** [comment]
Nintendo Switch games sometimes crash when they're continously restarted. At least this bug is not caused by the program itself...

**Comment by monkeybee11** [comment]
true ive ran it for a bit random qustion

is the time it waits before it takes a screenshot to check for colours 

on a timer or dose it wait for something?

im wondering bc when revewing the shiny check..py.......it took a lot of photos of my exeggutor not the shaymin >.< say it was like a 70/30ish  shaymin/exeggutor

**Comment by Dinones** [comment]
The program automatically detects the game has entered the combat by checking a line of pixels in this zone:

![image](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/assets/109595182/920dc07e-061c-47a1-ade5-69993a423ad9)

But before starting checking this line of pixels, it has to wait some seconds because the enter combat animation blinks and includes full white screen frames. Thus, there has to be a waiting time which is the constant OVERWORLD_ENTER_COMBAT_WAIT_SECONDS. All legendaries have different entering combat animations: some of them take more time, like giratina, and some others don't, like shaymin. Try decreasing the time a little bit, but not so much that it detects the white blink frame. Use printed messages in the terminal to help you know when the program starts checking those pixels and make sure it does not interfere with the loading screen.

**Comment by Dinones** [comment]
> HOW DID U GET A SHINY FOR THAT IMAGE XD and ok ill try setting that and running the program agen thanks 👍 setting it to a 8 seems to be a good number for shaymin so far havnt reviewed anything yet tho

It's a screenshot from a youtube video :). I'll also add this explanation to the instructions

**Comment by monkeybee11** [comment]
> > HOW DID U GET A SHINY FOR THAT IMAGE XD and ok ill try setting that and running the program agen thanks 👍 setting it to a 8 seems to be a good number for shaymin so far havnt reviewed anything yet tho
> 
> It's a screenshot from a youtube video :). I'll also add this explanation to the instructions

ahhhh ok ..... ive got my shiny shaymin today never thort about getting the screen shots from a youtube video was searching for hours on google images to try and find a good img for the colour picker >.<

off topic qustion any thorts about starting a github forum(not sure if thats locked behind a payed verion of github or not) or a discord server about this program just for random general talk insted of making useless issues ???

and me paniced when the shiny shaymin showed up and just yoinked the capture card out after all these resets didt want to risk the program not picking it up as a shiny >.< 😂

**Comment by Dinones** [comment]
> off topic qustion any thorts about starting a github forum(not sure if thats locked behind a payed verion of github or not) or a discord server about this program just for random general talk insted of making useless issues ???

I need to definitely create that discord channel, it'd be much better. Thanks for the idea.

> and me paniced when the shiny shaymin showed up and just yoinked the capture card out after all these resets didt want to risk the program not picking it up as a shiny >.< 😂

Happy to hear that! If you want to check whether the program would have detected the shiny or not, you can take the screenshot saved by the program in the `/Media/Results` folder and run the `Find_Color_Range.py` file. Once you have selected the image and the color ranges, try with the `Toggle Detection` button. A green rectangle should appear if it was a match.
