### ISSUE TITLE
Wild Encounter Search -- CAVE Related -- (Bug)

### ISSUE THREAD

**Issue by MCPika** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#40]
Sorry to be the bearer of bad news for today, but seems like when choosing the "Random Encounter". 
It has multiple issues: 
- The shiny was not seen 
- The name was not the good one either
- The program seems to stop sometimes while the control seems to try to be pressed

I posted a capture for you x')

![image](https://github.com/user-attachments/assets/0c0b2594-26de-405a-b05d-5b98c0381d59)

**Comment by MCPika** [comment]
Yeah it seems completely bugged look at the state of the program after 1 encounter

![image](https://github.com/user-attachments/assets/b6e3a1ce-2f47-425b-ac69-898cad6a0a78)

**Comment by MCPika** [comment]
![image](https://github.com/user-attachments/assets/3a72b55d-c60d-487e-9584-086313b7b4d6)

**Comment by MCPika** [comment]
https://github.com/user-attachments/assets/6b8cde0b-1902-48a4-a3ba-2ff5529a8dfc

Here's a video sample of what bugs I've encountered..And I wanted to show you the "Shiny thing" but i could have only if i had waited 30s more x')

**Comment by David34920** [comment]
Can you try to hunt with a non shiny Pokemon?

**Comment by David34920** [comment]
I have not tested wild encounters feature...
If you put back 1920x1280 did it works?

**Comment by Dinones** [comment]
Hi! Thank you for the video! Are you trying David34920's version, or the latest version of the shiny hunter?

**Comment by MCPika** [comment]
> Hi! Thank you for the video! Are you trying David34920's version, or the latest version of the shiny hunter?

Yeah I'm using David's program because I'm using the RaspBerry and If I can't turn off the Video Saving well I run the program at 4-5FPS and it's unbearable haha

Would you say that some part of it might altered how your code worked in the first place?

**Comment by Dinones** [comment]
I've noticed it's entering the `ESCAPE_COMBAT_5` state, which should only occur if running away fails. In the `ESCAPE_COMBAT_4` state, it checks for both the black pixels of the load screen and the white pixels of the life bar. It seems to be detecting the life bar incorrectly because the cave's background falls within the pixel range. Could you please test if this issue also occurs in the wild grass instead of a cave?

**Comment by MCPika** [comment]
> I've noticed it's entering the `ESCAPE_COMBAT_5` state, which should only occur if running away fails. In the `ESCAPE_COMBAT_4` state, it checks for both the black pixels of the load screen and the white pixels of the life bar. It seems to be detecting the life bar incorrectly because the cave's background falls within the pixel range. Could you please test if this issue also occurs in the wild grass instead of a cave?

Oh my lord I never thought about that let me try that out on the grass and record a video for you.

What would be the fix for the cave finding tho? Would it be to modify the pixel range depending On a choice of grass or cave finding?

**Comment by Dinones** [comment]
On another note, did you change something to make it work with dark mode? In the new video, I noticed the detection was done on a fully black screen, yet it still detected a white color.

**Comment by MCPika** [comment]
> On another note, did you change something to make it work with dark mode? In the new video, I noticed the detection was done on a fully black screen, but it still detected a white color.

So to be completely honest with you Dino I haven't notice the difference between the two videos. 
And the detection of the black scree actually is the detection of the first White screen frame when you launch the game just before the BDSP symbol, if it's of that you are talking about. 

> Could you please test if this issue also occurs in the wild grass instead of a cave?
Yes in grass it seems to be completely working so it's linked to the cave system and the darkness of the cave background maybe?
So maybe we will need to change the issue's title. Nice find @Dinones .

**Comment by Dinones** [comment]
> So to be completely honest with you Dino I haven't notice the difference between the two videos.
> And the detection of the black scree actually is the detection of the first White screen frame when you launch the game just before the BDSP symbol, if it's of that you are talking about.

You're right, it shouldn’t affect anything if it’s detecting the black load screen from the title.

> Yes in grass it seems to be completely working so it's linked to the cave system and the darkness of the cave background maybe?
> So maybe we will need to change the issue's title. Nice find @Dinones .

There you are. I figured this might happen a while ago, but I didn’t run into any errors until now. I know it’s a bit of a tedious, but could you let me know what output you get if you follow these steps with the color of the rocks?
- https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781

**Comment by MCPika** [comment]
> There you are. I figured this might happen a while ago, but I didn’t run into any errors until now. I know it’s a bit of a tedious, but could you let me know what output you get if you follow these steps with the color of the rocks?
> 
> * [Infinite loop in "RESTART_GAME_1" state #11 (comment)](https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781)

This is what I have as RGB colors (+ bonus I've answered in the closed issue #11 because I saw that normally it should have been fixed regarding the pairing that takes 2min30s +)
![image](https://github.com/user-attachments/assets/707e35ff-3085-4d01-ab55-ca9f4d725b9f)

**Comment by Dinones** [comment]
Well, I did not mean this at all, I just wanted to follow these instructions:
- https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11#issuecomment-2301964781
The exact moment to take the screenshot is when the state changes from `ESCAPE_COMBAT_4` to `ESCAPE_COMBAT_5`. The pixels you need to check manually are _(more or less, the surrounding ones should be similar)_ the ones where you see the purple line in the bottom-left corner. These pixels must be within the white color range, which is between (237, 237, 237) and (255, 255, 255).

> (+ bonus I've answered in the closed issue https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/issues/11 because I saw that normally it should have been fixed regarding the pairing that takes 2min30s +)

This occurs because your Nintendo Switch is set to dark mode. Switching it to light mode should solve the issue.

**Comment by MCPika** [comment]
> The exact moment to take the screenshot is when the state changes from `ESCAPE_COMBAT_4` to `ESCAPE_COMBAT_5`.

Omg this is gonna be a dousy....

**Comment by Dinones** [comment]
Yes, but don't worry I'll solve it by myself. Just keep in mind it doesn't work in caves for now. Leave this thread opened and I'll let you know when it's solved :)

**Comment by Dinones** [comment]
Hi @MCPika can you test whether the new PR @David34920 has just made solves the issue or not? I think the new way of detecting the white load screen he implemented for Arceus could have solved this issue too.

In order to download the latest version, you can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

**Comment by MCPika** [comment]
> Hi @MCPika can you test whether the new PR @David34920 has just made solves the issue or not? I think the new way of detecting the white load screen he implemented for Arceus could have solved this issue too.
> 
> In order to download the latest version, you can either clone the repository again `git clone https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter.git` or update the current one `git pull origin master` in your local repository folder.

Ok so that's very interesting imma go and check it out tonight if I have the time to download and make the modifications i need regarding to push notifications on discord instead of mail ^^

**Comment by Dinones** [comment]
Perfect, thank you! I really appreciate it! 😉

I have just restarted my game, and I'm not able to access any cave 😅. I'm catching shinies on the first route.

**Comment by MCPika** [comment]
Hi,
I know I have not came back to that thread for a long time because I wanted to catch Dialga shinny for a while now. 
And I was troubled because passing the 10k SR I was wondering why it didn't show itself YET. But as I wen higher now at 41k and passing. 
I checked the lost shinnies images and found out the program skipped 4 Dialga shinnies out of 600pool XD
SO IMMAGINE my suprise when i'm at 41K with no SHINY detection XD
STATIC_ENCOUNTERS_DELAY = 4
SHINY_DETECTION_TIME = 4.5 and I have tested out 4 with the same result.
So Dialga (before beating Elite  4) can be shiny hunted but seems there's no shiny detection ? what can i do?

**Comment by David34920** [comment]
Can you record a video of the app during the encounter phase?
The video must
- show the pink bars on the gameplay
- the current step

I caught it without any issue.

**Comment by MCPika** [comment]
> Can you record a video of the app during the encounter phase? The video must
> 
> * show the pink bars on the gameplay
> * the current step
> 
> I caught it without any issue.

Here I'm putting a screen of the image of the shiny which i found 6 copies in the folder XD at different time + video you asked of me ! 
I'm unlucky ? Btw thats the latest version of the pull master btw I forgot to actually mention it i think :/

![2024-11-14_16-56-49](https://github.com/user-attachments/assets/8a9c21c9-4a29-4cab-af6d-accb9aa67dad)

https://github.com/user-attachments/assets/7306b1b8-745b-4449-be69-625374636825

**Comment by David34920** [comment]
The video looks good to me...
Which value do you have for the shiny detect value? 2 or 2.5? It was 2.5 for a brief moment. Personally I always used 2

**Comment by MCPika** [comment]
> The video looks good to me... Which value do you have for the shiny detect value? 2 or 2.5? It was 2.5 for a brief moment. Personally I always used 2

Like said in the Constant.py file those are the input :/
STATIC_ENCOUNTERS_DELAY = 4
SHINY_DETECTION_TIME = 4.5
And it still doesn't detect :/

**Comment by David34920** [comment]
SHINY_DETECTION_TIME should not be edited that's your issue...

Put 2 for SHINY_DETECTION_TIME
And 4 for the delay

**Comment by Dinones** [comment]
David is right with the SHINY_DETECTION_TIME constant, it should not be edited from its default value (2). Nevertheless, the stars animation takes about 6s to complete, so as 4<6 I'm not 100% sure this is the issue.

Please, keep using the check_lost_shiny subprogram of the Image_Processing.py file to make sure you do not skip it again. Something is missing to me, as both David and me got it using the Shiny Hunter.

**Comment by MCPika** [comment]
> David is right with the SHINY_DETECTION_TIME constant, it should not be edited from its default value (2). Nevertheless, the stars animation takes about 6s to complete, so as 4<6 I'm not 100% sure this is the issue.
> 
> Please, keep using the check_lost_shiny subprogram of the Image_Processing.py file to make sure you do not skip it again. Something is missing to me, as both David and me got it using the Shiny Hunter.

yeah that worked XD im so dumb x') well dialga was caught by discord and now by me so im happy i'll finallybe able to test out the version in cave shinnies to see if that works @Dinones

**Comment by Dinones** [comment]
It's been a long time since this issue was opened, I can confirm commit https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/commit/d2d0079005af62f9063cef73f5eff7f6a6777762 solved it.
