### ISSUE TITLE
False Negative on Shiny Arceus

### ISSUE THREAD

**Issue by MMartin1211** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#44]
I was using the program to shiny hunt Arceus when the shiny appeared but was flagged as not shiny by the program. I'm guessing this is due to a timing issue as there is a cutscene that plays before the battle begins. The screenshot taken by the program shows that the pokemon is shiny, but the image is from right when the battle is starting and is very clouded due to the fade-in.

![1727567916](https://github.com/user-attachments/assets/f26a0f2b-e83b-4931-b0c5-a832d7bda1d5)

**Comment by David34920** [comment]
Hello Martin,
I'm currently hunting it, you have to update the value of 'SHINY_ENCOUNTERS_DELAY' to 9

It's not validated yet but it's seems working well for me.

I hope the next shiny you found the app will recognize it!

David

**Comment by MMartin1211** [comment]
Thank you @David34920, that does seem to help. The screenshot shows the "A wild Arceus appeared!" frame now. I'll update this thread if I'm able to confirm that the program can now detect the shiny.

**Comment by David34920** [comment]
I am using 8.5 now.
With 9, sometime the captured frame is my Pokémon instead of Arceus.

I'll also update the thread if I'm able to find the shiny Arceus :)

**Comment by MCPika** [comment]
@David34920 Yeah I'm having the same issue with a quirk XD 
I'm currently hunting Dialga once more but on the first time you ever see it and I wanted to shiny hunt it at this point in the game. But seems I need to make adjustments on the timer AND the fact that I need to move forward for that specific time.
Have you encountered that issue?

**Comment by David34920** [comment]
For Palkia, I have put 4 and it worked. But the same, 3.5 could be better.

About Arceus, I think there is more tweak to do, I believe I have encountered shinies but not detected because Arceus is white, and at some moments, the app checks for white pixels... I will do more tries and I will give my result here.

**Comment by Dinones** [comment]
> But seems I need to make adjustments on the timer AND the fact that I need to move forward for that specific time.
> Have you encountered that issue?

You should not have any issue moving forward. If you have the latest version of the program, it always moves forward for all static encounters; then, presses A until the player enters the combat so you will skip all the text interaction too.

**Comment by MCPika** [comment]
> You should not have any issue moving forward. If you have the latest version of the program, it always moves forward for all static encounters; then, presses A until the player enters the combat so you will skip all the text interaction too.

Yep I do have the latest version I just had forgotten to switch the Move_Static_Encounter variable from False to True
So its okay I adjusted xD

**Comment by David34920** [comment]
@MCPika you can try to use the code in this PR https://github.com/Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter/pull/48
Don't forget to update your constants to put 6.5 for the delay.

I'm currently testing it.

**Comment by David34920** [comment]
@MCPika I confirm the fix is working I found it

**Comment by MCPika** [comment]
> @MCPika I confirm the fix is working I found it

Well that's good to know ! Thx for your hard work !!
Ok then when i'll get to it i'll keep it in mind !

 Currently i'm struggling to get Palkia shiny (on first run) cuz the program just shuts down like every 300-600 retries and sometimes magically makes a 1k run out of the blue haha but i think that's just the raspberry working over time cuz if i did that on VM i think it might turn out bette r!

**Comment by Dinones** [comment]
@David34920 Thank you very much for your work! I've already pushed your PR to the main repository. 

@MCPika you should be able to download it now, and, as David said, increase the `STATIC_ENCOUNTERS_DELAY` constant of the `Constants.py` file to 6.5s.

On the other hand, I am interested in the Raspberry Pi functionality; if you finally try it out on your computer and the issue solves, please let me know. It could be really interesting to make it work on a Raspi. And please confirm you have downloaded the latest version of the program: a couple of weeks ago we solved the _"Nintendo going to sleep mode"_ issue, so this could be one reason.

**Comment by MCPika** [comment]
> @David34920 Thank you very much for your work! I've already pushed your PR to the main repository. 
> 
> @MCPika you should be able to download it now, and, as David said, increase the `STATIC_ENCOUNTERS_DELAY` constant of the `Constants.py` file to 6.5s.
> 
> On the other hand, I am interested in the Raspberry Pi functionality; if you finally try it out on your computer and the issue solves, please let me know. It could be really interesting to make it work on a Raspi. And please confirm you have downloaded the latest version of the program: a couple of weeks ago we solved the _"Nintendo going to sleep mode"_ issue, so this could be one reason.

@Dinones yeah i'll be happy to test it out on Arceus when I get to him ^^ but like I said rn im trying another save to get the 3leg i did not have before going further into the main storyline ^^

As for the raspberry well idk if its the issue regarding the "going to sleep" issue because when i tested out with the starters I hadn't face this issue at that time and I hadn't updated the project since the starter shiny hunt. But imma try it out both on pc and raspberry with the new content you pushed.

But imma modify it a bit because instead of pushing through mails im pushing it through Discord which is somehow way better 😊

**Comment by Dinones** [comment]
> @Dinones yeah i'll be happy to test it out on Arceus when I get to him ^^ but like I said rn im trying another save to get the 3leg i did not have before going further into the main storyline ^^

Sure, don't worry, I have the same issue, I restarted my main save and I'm just at the beginning of the story, on the first routes, so I can barely test nothing

> As for the raspberry well idk if its the issue regarding the "going to sleep" issue because when i tested out with the starters I hadn't face this issue at that time and I hadn't updated the project since the starter shiny hunt. But imma try it out both on pc and raspberry with the new content you pushed.

Perfect, thank you! Don't hurry; it's just experimental for me to know :)

> But imma modify it a bit because instead of pushing through mails im pushing it through Discord which is somehow way better 😊

Sound good! We were implementing Telegram now, but Discord was in my mind too. What are you doing exactly? Sending messages when a shiny is found, like the emails, or also accepting incoming messages to ping the bot, ask for a screenshot, etc?

**Comment by MCPika** [comment]
> > Sure, don't worry, I have the same issue, I restarted my main save and I'm just at the beginning of the story, on the first routes, so I can barely test nothing

Yeah ive not done that because im still using the latest version of BDSP but once ive acquired the shinnies i want imma reset everything and clear out everything to get back to v1.1.0 for all the glitches to get my hands on the pkmn i can't get in v1.3.0

> > Perfect, thank you! Don't hurry; it's just experimental for me to know :)

Yeah dw I could try and video tape that through SNAGIT to see what seems to be the issue but imma try on VM as well to see how the project responds ^^

> > Sound good! We were implementing Telegram now, but Discord was in my mind too. What are you doing exactly? Sending messages when a shiny is found, like the emails, or also accepting incoming messages to ping the bot, ask for a screenshot, etc? 

For now I'm using one the PR which was like 3month old just to push the notification of "hey you've got a shiny" which i modified to my convenience and catching the name of the pkm as well. But I wanted to further develop it when the time is permitted and catch errors (now i just know when there is an error because my dock is just turned off whenever its gone to sleep xd) and send the screen (watch the size of the img i might want to take the screens and save them as .webpp instead of .png)

**Comment by Dinones** [comment]
> Yeah ive not done that because im still using the latest version of BDSP but once ive acquired the shinnies i want imma reset everything and clear out everything to get back to v1.1.0 for all the glitches to get my hands on the pkmn i can't get in v1.3.0

Is it possible to rollback to a previous version of the game? 
What pokémon are unobtainable on newer versions?

> For now I'm using one the PR which was like 3month old just to push the notification of "hey you've got a shiny" which i modified to my convenience and catching the name of the pkm as well. But I wanted to further develop it when the time is permitted and catch errors (now i just know when there is an error because my dock is just turned off whenever its gone to sleep xd) and send the screen (watch the size of the img i might want to take the screens and save them as .webpp instead of .png)

Oh perfect! Don't worry, take your time. I'll work on it eventually too, so if you do a PR before, I'll accept and work with it, and if not, I'll start by myself. I have experience with Discord bots too :)

**Comment by MMartin1211** [comment]
I haven't commented in a while, but I wanted to update that I just successfully got the shiny Arceus! The 9 second delay worked perfectly for me. For some reason the program didn't take a screenshot of the shiny, but it did recognize the shiny and shut down properly.
