### ISSUE TITLE
Arceus encounter not working 

### ISSUE THREAD

**Issue by TheBock123** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#62]
Hi Im currently shiny hunting Arceus and noticed that after the controller connects it will load into the game but not move forward to start the encounter. it has worked previously but I have to restart the virtual box over and over to try and get it to start the inputs once it loads into the game.

**Comment by TheBock123** [comment]
> Hi @TheBock123! Could you please check #21 and tell me if it solves the issue?

hi yes it has been changed it has worked previously but not sure why it wont work now. after the controller connects it will press into the game but still wont walk forward

**Comment by Dinones** [comment]
When the program enters the game, do you see the UP button colored before starting pressing A in the controller image next to the game?

**Comment by TheBock123** [comment]
Now the controller connects but doesnt start any inputs to load the game it just stays in the controller change grip/order

**Comment by Dinones** [comment]
Hmm, the bluetooth system may be bugged, please restart your computer (the whole computer, not just the VM) and try again to see if the UP button is pressed.

**Comment by Dinones** [comment]
Closed due to @TheBock123 not responding.
