### ISSUE TITLE
Controller Not Pairing

### ISSUE THREAD

**Issue by ReZeroPlat** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#9]
when starting the Shiny_Hunter.py command the screen remains stuck at the pairing screen where im able to read current state: WAITING_PAIRING_SCREEN but im there and no idea

**Comment by Dinones** [comment]
Please, can you answer the following question:

1. Does the controller connect to the Nintendo Switch?
2. Are you using any Nintendo Switch theme? Like dark mode or any other one (custom/animated themes) that is not the light mode?
3. Can you please provide a screenshot of the program?

**Comment by ReZeroPlat** [comment]
when I run the command python3 Switch_Controller.py it doesnt ask me to pair it crash and in the terminal this appear:
Option 1 selected: Testing Switch Controller...
Restarting bluetooth systems...
Bluetooth restarted successfully!
Releasing 3 thread(s)...

im in light mode and at the moment i cannot provide a screenshot

**Comment by Dinones** [comment]
Just to be sure, 
1. Did you connect your bluetooth card to the virtual machine?
2. Did you follow all the steps of the installation guide for the virtual machine?
3. If yes, what step did you get stuck on?

**Comment by ReZeroPlat** [comment]
yes the card is connected to the vm
yes i have followed all the steps excluded some "extra"

**Comment by ReZeroPlat** [comment]
just one thing, I haven't configured the shiny colors because I don't understand how to do it

**Comment by Dinones** [comment]
Hi! The newest version automatically detects the shiny pokémon so you don't need to configure the shiny colors anymore. Regarding the controller connection, it is related to the nxbt library. Can you please follow these steps in order to identify the issue:

1. Run `sudo pip3 install nxbt`.
2. Navigate back to the "Change Grip/Order Menu" of the Nintendo Switch and make sure any joycon is connected to it.
3. Run `sudo nxbt demo` and provide me the console output.

**Comment by ReZeroPlat** [comment]
This is what I get

Traceback (most recent call last):
  File "/usr/local/bin/nxbt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 325, in main
    demo()
  File "/usr/local/lib/python3.8/dist-packages/nxbt/cli.py", line 154, in demo
    raise OSError("Unable to detect any Bluetooth adapters.")
OSError: Unable to detect any Bluetooth adapters.

**Comment by Dinones** [comment]
You are encountering the issue "No Available Adapters" explained in the nxbt repository (https://github.com/Brikwerk/nxbt?tab=readme-ov-file#no-available-adapters). It seems the virtual machine is not detecting your bluetooth card.

1. Is your Bluetooth adapter appearing and checked in this menu (your adapter may have a different name)?
ㅤ
![image](https://github.com/user-attachments/assets/5aef95e9-3ee6-4e7a-86cc-c866e8b2ea64)

2. Can you see the bluetooth icon at the top-left corner of the virtual machine as shown in this image?
ㅤ
![image](https://github.com/user-attachments/assets/47367da1-5885-4cd8-874b-c211dfb8b83a)

3. Run the following commands:

a. Make sure BlueZ is installed:
  ```bash
  sudo apt update
  sudo apt install bluez 
  sudo apt install bluez-tools
``` 
b. Check the Bluetooth service is enabled:
```bash
sudo systemctl start bluetooth
sudo systemctl enable bluetooth
sudo systemctl status bluetooth
```
You should see the words "active (running)" in green

c. If your Bluetooth is working, run:
```bash
bluetoothctl list
hciconfig -a
```
If your Bluetooth adapter is working, you should see details about it, including its MAC address and other information.

**Comment by ReZeroPlat** [comment]
It doesn't seem to work, the bluetooth is running but the controller gives to me the same problem

**Comment by ReZeroPlat** [comment]
ok i have found a solution:

cd /usr/lib/firmware/rtl_bt
sudo ln -s rtl8761b_fw.bin rtl8761bu_fw.bin

If you are missing the original file, you can download it from a GitHub repository. For Realtek devices it would be
https://github.com/Realtek-OpenSource/android_hardware_realtek/tree/rtk1395/bt/rtkbt/Firmware/BT
